"""add grounding metrics and token governance

Revision ID: c1a92e5d8b3f
Revises: b0b70ff29749
Create Date: 2026-08-23 09:30:00.000000

Implements the "métricas estruturadas anti-alucinação" half of
docs/mapa-chat-widget-metricas-tokens.md:

- diagnosis_requests.possibly_ungrounded: session-level flag, true only when
  no turn in the session ever retrieved a knowledge-base chunk.
- diagnosis_turn_metrics: one row per assistant reply, recording which
  chunks were retrieved for grounding and the input/output token counts for
  that turn, instead of discarding LLMResponse.usage like before.

Hand-authored (not autogenerated) -- this working copy has no live
Postgres+pgvector instance to run `alembic revision --autogenerate` against.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1a92e5d8b3f'
down_revision: str | None = 'b0b70ff29749'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'diagnosis_requests',
        sa.Column('possibly_ungrounded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('diagnosis_requests', 'possibly_ungrounded', server_default=None)

    op.create_table(
        'diagnosis_turn_metrics',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('diagnosis_session_id', sa.Uuid(), nullable=False),
        sa.Column('assistant_message_id', sa.Uuid(), nullable=False),
        sa.Column('chunks_retrieved', sa.JSON(), nullable=False),
        sa.Column('chunks_used_count', sa.Integer(), nullable=False),
        sa.Column('input_tokens', sa.Integer(), nullable=True),
        sa.Column('output_tokens', sa.Integer(), nullable=True),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(['diagnosis_session_id'], ['diagnosis_sessions.id']),
        sa.ForeignKeyConstraint(['assistant_message_id'], ['diagnosis_messages.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_diagnosis_turn_metrics_diagnosis_session_id'),
        'diagnosis_turn_metrics',
        ['diagnosis_session_id'],
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_diagnosis_turn_metrics_diagnosis_session_id'), table_name='diagnosis_turn_metrics'
    )
    op.drop_table('diagnosis_turn_metrics')
    op.drop_column('diagnosis_requests', 'possibly_ungrounded')
