"""create initial schema

Revision ID: fa3693a4f9df
Revises: 
Create Date: 2026-08-15 21:33:28.163486

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa3693a4f9df'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('chat_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_session_id'), 'chat_conversations', ['session_id'], unique=False)
    op.create_table('diagnosis_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_sessions_session_id'), 'diagnosis_sessions', ['session_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('diagnosis_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_session_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_messages_diagnosis_session_id'), 'diagnosis_messages', ['diagnosis_session_id'], unique=False)
    op.create_table('diagnosis_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_session_id', sa.Uuid(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('problem_summary', sa.Text(), nullable=False),
    sa.Column('services_of_interest', sa.JSON(), nullable=False),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('raw_transcript_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_session_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_session_id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('diagnosis_requests')
    op.drop_index(op.f('ix_diagnosis_messages_diagnosis_session_id'), table_name='diagnosis_messages')
    op.drop_table('diagnosis_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_diagnosis_sessions_session_id'), table_name='diagnosis_sessions')
    op.drop_table('diagnosis_sessions')
    op.drop_index(op.f('ix_chat_conversations_session_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
